//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Year { get; set; }
        public string Information { get; set; }
        public object Info { get; internal set; }
    }
}
